#+OPTIONS: num:nil

* TG-Focus

tg-focus is a Telegram message forwarder/filter. By customizing /Focus
Filters/, tg-focus can 
forward any specific message in any specific chat, to one
dedicated chat, so that users have fully control on the messages they
will see.

Telegram is famous for its openness, while users are free to make a
speech in any public chat, they should be free to choose what they'd
see. Telegram's official client apps has comprehensive support for the
former feature, tg-focus will try its best to fill the blank in the
latter one. 

Notable features:

- **Reliable & Consistent**: Built on top of official telegram client
  library - TDLib. All communications towards Telegram servers are
  completely handled by TDLib.

- **Customizable**: Users can customize their /Focus Filters/ in any
  time. The filter accepts both raw simple text and regular
  expression.

- **Ready to deploy**: tg-focus releases are in three forms: source,
  binary and OCI image. Users can run it directly on a laptop,
  or use docker/podman to deploy it on their servers, without even
  interfering with each other.

Limitations:

- tg-focus only support text messages(including text, emoji,
  and the media caption).

* Filtering Rules

/Focus Filter/ is a filter used by tg-focus to match against the
message's text content(raw text, emoji, or media caption). There can
be many filters, when a message comes, they are tried one by one, if
there is any filter than can /match/ the message, it will be
forwarded.

Currently /Focus Filter/ can match

1. Chat title
2. Text keywords
3. Message senders
4. Text non-keywords
5. Message non-senders

A /Focus Filter/ is matched if and only if:

- the message does match any of the above 1~3 items.
- the message does NOT match any of the above 4~5 items.

(Hence, 1/2/3 can be regarded as a *whitelist* filter, 4/5 can be
regarded as a *blacklist* filter.)

** Examples

Say we want to forward all messages in a chat named "👍AnAwesomeChat👍",
any of the following configurations works:

(works, the chat title is fully matched: )
#+begin_src toml
  [[focus-filter]]
  title = "👍AnAwesomeChat👍"
#+end_src

(works, the chat title is partly matched: )
#+begin_src toml
  [[focus-filter]]
  title = "AnAwesomeChat"
#+end_src

(works, the chat title is partly matched: )
#+begin_src toml
  [[focus-filter]]
  title = "Awesome"
#+end_src

(works, the chat title is partly matched: )
#+begin_src toml
  [[focus-filter]]
  title = "👍"
#+end_src

(works, the regular expression matches the chat title: ) 
#+begin_src toml
  [[focus-filter]]
  title = ".*Awesome.*"
#+end_src

Say we want to forward the messages that contain "football", but not
"basketball", from a chat named "Sports User Group". We can write our filters as

#+begin_src toml
  [[focus-filter]]
  title = "Sports User Group"
  keywords = ["football", "soccer"]
  no-keywords = ["basketball"]
#+end_src

or if we want the messages containing "football", or any other
messages except the ones containing "basketball", from a chat named
"SportsUserGroup". We can write the filter as

#+begin_src toml
  # 1st
  [[focus-filter]]
  title = "Sports User Group"
  keywords = ["football", "soccer"]

  # 2nd
  [[focus-filter]]
  title = "Sports User Group"
  no-keywords = ["basketball"]
#+end_src

So these message will be forwarded: =I love football!= (matching the 1st),
=I play soccer= (matching the 1st), =I am good at swimming= (matching the
2nd), =Sometime I also play badminton= (matching the 2nd).

These will NOT be forwarded: =I play football and basketball= (not
matching any), =any one wants to play basketball?= (not matching any).





