FROM debian:12 AS builder

ARG URL_RELTGZ_AMD64
ARG URL_RELTGZ_ARM64

RUN mkdir /opt/playground
RUN mkdir /opt/tg-focus
WORKDIR /opt/playground

RUN apt-get update && \
    apt-get install -y wget tar && \
    rm -rf /var/lib/apt/lists/*

RUN test $TARGETPLATFORM == "linux/amd64" && URL_RELTGZ=$URL_RELTGZ_AMD64
RUN test $TARGETPLATFORM == "linux/arm64" && URL_RELTGZ=$URL_RELTGZ_ARM64

RUN wget "${URL_RELTGZ}" -O tg-focus-3.0-linux.tar.gz && \
        tar xvf tg-focus-3.0-linux.tar.gz --strip-components=1 -C /opt/tg-focus

FROM debian:12-slim


RUN apt-get update && \
    apt-get install -y locales && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i 's/# en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen

RUN locale-gen

RUN mkdir /opt/tg-focus
COPY --from=builder /opt/tg-focus /opt/tg-focus/

ENV PATH="/opt/tg-focus:$PATH"
RUN mkdir -p /root/.tgfocus/3 && touch /root/.tgfocus/3/child_coll.log

RUN echo "#!/bin/bash" >> /usr/local/bin/version
RUN echo "tgfocus version" >> /usr/local/bin/version
RUN chmod +x /usr/local/bin/version

RUN echo "#!/bin/bash" >> /usr/local/bin/status
RUN echo "tgfocus status" >> /usr/local/bin/status
RUN chmod +x /usr/local/bin/status

RUN echo "#!/bin/bash" >> /usr/local/bin/auth
RUN echo "tgfocus auth" >> /usr/local/bin/auth
RUN chmod +x /usr/local/bin/auth

ENTRYPOINT ["/bin/bash","-c","tgfocus quickstart && tail -f /root/.tgfocus/3/child_coll.log"]