
* Requirement

- Unix (Linux or BSDs)
- Bash (any version)
- Git (any version)
- GCC (version >= 11) or LLVM Clang (version >= 11)
- CMake (version >= 3.5)
  
** Third-party dependencies

- TDLib (https://github.com/tdlib/td, using version specified in
  =pick-ver-tdlib= and =pick-src-tdlib=)
- toml11 (https://github.com/ToruNiina/toml11, using version specified
  in =pick-src-toml11=)

* Essential Files

- =i18n.csv=: internationalization configuration.
  
- =sync-versions.bash=: synchronize versions embedded in source files,
  versions are:
  - =pick-src-tdlib=: the linkage of TDLib targeted by tg-focus.
  - =pick-ver-tdlib=: the version of TDLib targeted by tg-focus.
  - =pick-ver-tgfocus=: the current release version of tg-focus.
    
  Note: running the script should result in no effect most of the
  time, because picking versions should be an infrequent operation.
  
- =deb10-gcc12.bash=: a script that prepares the dedicated
  toolchain(GCC) on the dedicated platform(Debian).
  
  Note: the corresponding preparation steps in CICD workflow must sync
  with this file.

  
* Building & Testing

*Notice:* Before building tg-focus, make sure TDLib is installed
properly and the installed one's version should match =pick-ver-tdlib=
and =pick-src-tdlib= *exactly*. Otherwise prepare specific version
indicated by =pick-ver-tdlib= and =pick-src-tdlib=, and then follow
the installation instructions provided by TDLib:
https://tdlib.github.io/td/build.html

#+begin_src bash

  # Download third party dependencies. Network connection required.
  bash dev/install-deps-oci-only.bash

  # Setup a debug build.
  cmake -B build
  # or a release build.
  cmake -DCMAKE_BUILD_TYPE=Release -B build

  # Build.
  cd build && make -j$(nproc)

  # Test. UTC timezone is required.
  cd build && TZ=UTC make test

#+end_src

