#ifndef hh_errcode
#define hh_errcode

#include "std_comp.hh"

namespace tgf {

enum ErrCode : u8
{
  NOERR = 0,
  IPCSERVER_SYSCALL_SOCKET,
  IPCSERVER_SYSCALL_SOCKOPT,
  IPCSERVER_SYSCALL_BIND,
  IPCSERVER_SYSCALL_LISTEN,
  IPCSERVER_SYSCALL_SOCKET2,
  IPCSERVER_SYSCALL_BIND2,
  IPCSERVER_SYSCALL_LISTEN2,
  CONNLISTENER_SYSCALL_ACCEPT,
  CONNLISTENER_SOCKREADY,
  CONNLISTENER_SYSCALL_EPCREAT,
  CONNLISTENER_SYSCALL_EPCTL,
  CONNLISTENER_SYSCALL_EPCTL2,
  CONNLISTENER_SYSCALL_EPWAIT,
  CONNLISTENER_SYSCALL_THREAD,
  IPCCONNHAND_SYSCALL_EPCREAT,
  IPCCONNHAND_SYSCALL_EPCTL,
  IPCCONNHAND_SYSCALL_EPWAIT,
  IPCCONNHAND_SYSCALL_READ,
  IPCCONNHAND_SYSCALL_SEND,
  IPCCONNHAND_SYSCALL_SEND2,
  IPCCLIENT_SYSCALL_SOCKET,
  IPCCLIENT_SYSCALL_CONNECT,
  IPCCLIENT_SYSCALL_SOCKET2,
  IPCCLIENT_SYSCALL_CONNECT2,
  IPCCLIENT_SYSCALL_READ,
  IPCCLIENT_SYSCALL_WRITE,
  IPCCLIENT_MUSTVALIDIPCMSG,
  IPCMSG_MUSTVALIDIPCMSG,
  IPCSRCINITER_SYSCALL_THREAD,
  TGFOCUS_SYSCALL_THREAD,
  TGFOCUS_SYSCALL_THREAD2,
  TGFOCUS_SYSCALL_THREAD3,
};

inline ostream &
operator<< (ostream &os, const ErrCode &self)
{
  os << scast<int> (self);
  return os;
}

using EC = ErrCode;

} // namespace tgf

#endif
