name: Manual Build
run-name: Manual Build triggered by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      artifacts_url:
        description: "URL to the artifact to build"
        required: true
        default: ""
        type: string
      platform:
        description: "Target platform for the build"
        required: true
        type: choice
        options:
          - linux/amd64
          - linux/arm64
      tag:
        description: "Custom tag (optional)"
        required: false
        default: ""
        type: string

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: read
      id-token: write
    steps:
      - name: Workflow info
        run: |
          echo "Workflow triggered by: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event inputs: ${{ toJson(github.event.inputs) }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: tag
        id: tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "No custom tag provided, using commit SHA."
            echo "tag=${{ github.sha }}-${{ github.event.inputs.platform }}" >> $GITHUB_ENV
          else
            echo "Using custom tag: ${{ github.event.inputs.tag }}"
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./ci/Containerfile
          platforms: ${{ github.event.inputs.platform }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tg-focus:${{ env.tag }}
          build-args: |
            ARTIFACTS_URL=${{ github.event.inputs.artifacts_url }}
            TAG=${{ env.tag }}
