name: create-github-package
on:
  workflow_dispatch:
    inputs:
      url_tgz_amd64:
        description: "Release tarball for amd64"
        required: true
        default: ""
        type: string
      url_tgz_arm64:
        description: "Release tarball for arm64"
        required: true
        default: ""
        type: string
      tag:
        description: "Custom tag (optional)"
        required: false
        default: ""
        type: string

jobs:
  job1:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
      attestations: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Workflow info
        run: |
          echo "Workflow triggered by: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event inputs: ${{ toJson(github.event.inputs) }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: determine tgz url
        run: |
	  if [[ "${{ matrix.platform }}" == linux/amd64 ]]
	  then
	    echo "url_tgz=${{ github.event.inputs.url_tgz_amd64 }}" >> $GITHUB_ENV
	  fi
	  if [[ "${{ matrix.platform }}" == linux/arm64 ]]
	  then
	    echo "url_tgz=${{ github.event.inputs.url_tgz_arm64 }}" >> $GITHUB_ENV
	  fi

      - name: determine image tag
        id: tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "No custom tag provided, using commit SHA."
            echo "tag=${{ github.sha }}-${{ github.event.inputs.platform }}" >> $GITHUB_ENV
          else
            echo "Using custom tag: ${{ github.event.inputs.tag }}"
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./ci/Containerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tg-focus:${{ env.tag }}
          build-args: |
            ARTIFACTS_URL=${{ env.url_tgz }}
            TAG=${{ env.tag }}
