name: build-toolc-gcc12-deb11-x64
run-name: Build toolc-gcc12-deb11-x64
on:
  push:
    branches:
      - master

jobs:
  job1:
    if: contains(github.event.head_commit.message, 'build-tgfocus-x64-linux-musl') == true
    runs-on: ubuntu-24.04
    steps:
      - name: Set env
        run: echo "CURR_DATE=$(date +'%Y%m%d')" >> "$GITHUB_ENV"
      - name: Set env
        run: echo "PICK_TAG=gcc12-deb11-x64" >> "$GITHUB_ENV"
      - name: Set env
        run: echo "OCIIMG_NAME=tg-focus-cicd-toolc" >> "$GITHUB_ENV"
      - run: sleep 10s
      - run: df -h
      - run: buildah from docker.io/library/alpine:3.21
      - run: buildah run alpine-working-container -- cat /etc/os-release
      - run: buildah run alpine-working-container -- apk add sudo git bash
      - run: buildah run alpine-working-container -- git clone --depth=1 https://github.com/micl2e2/tg-focus
      - run: buildah run alpine-working-container -- bash -c "cd tg-focus && bash ci/prep-libs-alp321-x64.bash"
      - run: buildah run alpine-working-container -- bash -c "cd tg-focus && bash ci/build-tgfocus-alp321-x64.bash"
      - run: buildah run alpine-working-container -- bash -c "cd tg-focus && bash ci/pack-tgfocus-alp321-x64.bash"
      - run: buildah ps
      - run: buildah commit alpine-working-container tmp
      - run: podman run --name=tmp tmp
      - run: podman cp tmp:/tg-focus/ci/tgfocus-linux-musl-x64.tgz .
      - run: podman cp tmp:/tg-focus/ci/CHECKSUM-tgfocus-linux-musl-x64.tgz .
      - uses: actions/upload-artifact@v4
        with:
          name: tgfocus-linux-musl-x64.tgz
          path: ci/tgfocus-linux-musl-x64.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: CHECKSUM-tgfocus-linux-musl-x64.tgz
          path: ci/CHECKSUM-tgfocus-linux-musl-x64.tgz
